apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zlth227si-python 
  janus-idp.io/tekton: zlth227si-python
  backstage.io/kubernetes-id: zlth227si-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zlth227si-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  